AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  # ImageLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: ImageLayer
  #     ContentUri: /app/layer
  #     RetentionPolicy: Retain      
  #     CompatibleRuntimes: 
  #       - nodejs8.10

  ImageResizer:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment: 
        Variables:
          FARTS: 'stinky'
          AWS_ACCESS_KEY_ID: 'fake'
          AWS_SECRET_ACCESS_KEY: 'fake'
          PG_URI: 'postgres://postgres:postgres@pg:5432/carpedalan'
          IS_LOCAL: true
          REDIS_URL: redis://redis:6379/0
      CodeUri: ./src/
      Handler: image.imageResizer
      Runtime: nodejs12.x
      # Layers: 
      #   - Ref: ImageLayer
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post

  Redis:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment: 
        Variables:
          FARTS: 'stinky'
          AWS_ACCESS_KEY_ID: 'fake'
          AWS_SECRET_ACCESS_KEY: 'fake'
          PG_URI: 'postgres://postgres:postgres@pg:5432/carpedalan'
          IS_LOCAL: true
          REDIS_URL: redis://redis:6379/0
      CodeUri: ./src/
      Handler: sns.sns
      Runtime: nodejs12.x
